app = "aged-night-9426"
primary_region = "ams"
swap_size_mb = 256

[env]
  SERVER_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[metrics]
  port = 8080
  path = "/actuator/prometheus"
